baseURL = ""
title = "New Homepage"

theme = "aosc_new_era"

defaultContentLanguage = 'en'
languageCode = "en-us"
defaultContentLanguageInSubdir = false
hasCJKLanguage = true

[languages]
  [languages.en]
    contentDir = 'content'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Fallback Title'
    weight = 1
    [languages.en.params]
      subtitle = '---'
  [languages.cn]
    contentDir = 'content'
    disabled = false
    languageCode = 'zh-CN'
    languageDirection = 'ltr'
    languageName = '简体中文'
    title = 'Title 中文'
    weight = 2
    [languages.cn.params]
      subtitle = 'subtitle'

[markup]
  [markup.highlight]
    style = "monokailight"
